var song_list ={
    "01":{
        title: "16",
        artist: "Baby Keen",
        genre: "Pop",
        duration: "2.37",
        track:"16.mp3",
    },
    "02":{
        title: "Honest",
        artist: "Baby Keen",
        genre: "Pop",
        duration: "3.06",
        track:"Honest.mp3",
    },
    "03":{
        title: "Toosie Slide",
        artist: "Drake",
        genre: "Pop",
        duration: "4.07",
        track:"Toosie Slide.mp3",
    },
    "04":{
        title: "Heave and Hell",
        artist: "Kanye West",
        genre: "Pop",
        duration: "2.25",
        track:"Heaven and Hell.mp3",
    },
    "05":{
        title: "Mafia",
        artist: "Travis Scott",
        genre: "Pop",
        duration: "4.01",
        track:"MAFIA.mp3",
    },
    "06":{
        title: "Baddal",
        artist: "Jasmien Sandles",
        genre: "Pop",
        duration: "4.03",
        track:"Baddal.mp3",
    },
    "07":{
        title: "Orange Soda",
        artist: "Baby Keem",
        genre: "Pop",
        duration: "2.26",
        track:"Orange Soda.mp3",
    },
    "08":{
        title: "Vent",
        artist: "Baby Keem",
        genre: "Pop",
        duration: "2.18",
        track:"Vent.mp3",
    },
    "09":{
        title: "Praise Lord",
        artist: "Kanye West & Baby Keem",
        genre: "Pop",
        duration: "3.37",
        track:"Praise Lord.mp3",
    },
    "10":{
        title: "Wants & Needs",
        artist: "Drake ft. Lil Baby",
        genre: "Pop",
        duration: "4.47",
        track:"Drake ft. Lil Baby _Wants and Needs_ (Music Video)(MP3_128K)_1",
    },

}